[tool.poetry]
name = "fastaplab1"
version = "0.1.0"
description = ""
authors = ["BohdanMatiushko <zerox2007ss@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.128.8"
uvicorn = "^0.40.0"
email-validator = "^2.3.0"
sqlalchemy = "^2.0.48"
asyncpg = "^0.31.0"
alembic = "^1.18.4"
pydantic-settings = "^2.13.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}

[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"
pytest-asyncio = "^0.23.3"
httpx = "^0.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
